// <auto-generated />
using Database.Data.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ArtContext))]
    partial class ArtContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CivicNumber")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Pesaro",
                            CivicNumber = 2,
                            Country = "Italy",
                            Street = "via delle Fornaci"
                        },
                        new
                        {
                            Id = 2,
                            City = "Pistoia",
                            CivicNumber = 22,
                            Country = "Italy",
                            Street = "via San Sebastiano"
                        },
                        new
                        {
                            Id = 3,
                            City = "Oviedo",
                            CivicNumber = 13,
                            Country = "Spain",
                            Street = "via del Commercio"
                        },
                        new
                        {
                            Id = 4,
                            City = "Damasco",
                            CivicNumber = 17,
                            Country = "Syria",
                            Street = "via Mercatore"
                        });
                });

            modelBuilder.Entity("Database.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfBirth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bryant",
                            YearOfBirth = 1990
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jordan",
                            YearOfBirth = 1990
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jokic",
                            YearOfBirth = 1990
                        },
                        new
                        {
                            Id = 4,
                            Name = "Smart",
                            YearOfBirth = 1990
                        });
                });

            modelBuilder.Entity("Database.Models.Exhibition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exhibitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gli animali nella pittura del 1900"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Le città nel postimpressionismo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Il sacro nel 900"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ritratti di donna nel corso dei secoli"
                        });
                });

            modelBuilder.Entity("Database.Models.ExhibitionPainting", b =>
                {
                    b.Property<int>("ExhibitionId")
                        .HasColumnType("int");

                    b.Property<int>("PaintingId")
                        .HasColumnType("int");

                    b.HasKey("ExhibitionId", "PaintingId");

                    b.HasIndex("PaintingId");

                    b.ToTable("ExhibitionPainting");

                    b.HasData(
                        new
                        {
                            ExhibitionId = 1,
                            PaintingId = 1
                        },
                        new
                        {
                            ExhibitionId = 1,
                            PaintingId = 2
                        },
                        new
                        {
                            ExhibitionId = 2,
                            PaintingId = 3
                        },
                        new
                        {
                            ExhibitionId = 2,
                            PaintingId = 4
                        },
                        new
                        {
                            ExhibitionId = 3,
                            PaintingId = 5
                        },
                        new
                        {
                            ExhibitionId = 3,
                            PaintingId = 6
                        },
                        new
                        {
                            ExhibitionId = 4,
                            PaintingId = 7
                        },
                        new
                        {
                            ExhibitionId = 4,
                            PaintingId = 8
                        });
                });

            modelBuilder.Entity("Database.Models.Museum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Museums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Name = "Museo dei Fiori"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 3,
                            Name = "Gran Museo della Ragione"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 4,
                            Name = "Museo di Arte Maggiore"
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 2,
                            Name = "Il Laboratorio della Mente"
                        });
                });

            modelBuilder.Entity("Database.Models.Painting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfCreation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("MuseumId");

                    b.ToTable("Paintings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            MuseumId = 1,
                            Title = "Vita dei campi",
                            YearOfCreation = 1920
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 1,
                            MuseumId = 3,
                            Title = "Spiaggia Lunare",
                            YearOfCreation = 1921
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 2,
                            MuseumId = 2,
                            Title = "Montagna di sale",
                            YearOfCreation = 1922
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 2,
                            MuseumId = 4,
                            Title = "La stella più lontana",
                            YearOfCreation = 1923
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 3,
                            MuseumId = 1,
                            Title = "L'artiglio di ghiaggio",
                            YearOfCreation = 1924
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 3,
                            MuseumId = 3,
                            Title = "Lo sguardo della madre",
                            YearOfCreation = 1925
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 4,
                            MuseumId = 2,
                            Title = "La mano del padre",
                            YearOfCreation = 1926
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 4,
                            MuseumId = 4,
                            Title = "Velocità",
                            YearOfCreation = 1927
                        });
                });

            modelBuilder.Entity("Database.Models.ExhibitionPainting", b =>
                {
                    b.HasOne("Database.Models.Exhibition", "Exhibition")
                        .WithMany("Paintings")
                        .HasForeignKey("ExhibitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.Painting", "Painting")
                        .WithMany("Exhibitions")
                        .HasForeignKey("PaintingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exhibition");

                    b.Navigation("Painting");
                });

            modelBuilder.Entity("Database.Models.Museum", b =>
                {
                    b.HasOne("Database.Models.Address", "Address")
                        .WithOne("Museum")
                        .HasForeignKey("Database.Models.Museum", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Database.Models.Painting", b =>
                {
                    b.HasOne("Database.Models.Artist", "Artist")
                        .WithMany("Paintings")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.Museum", "Museum")
                        .WithMany("Paintings")
                        .HasForeignKey("MuseumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Museum");
                });

            modelBuilder.Entity("Database.Models.Address", b =>
                {
                    b.Navigation("Museum")
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Models.Artist", b =>
                {
                    b.Navigation("Paintings");
                });

            modelBuilder.Entity("Database.Models.Exhibition", b =>
                {
                    b.Navigation("Paintings");
                });

            modelBuilder.Entity("Database.Models.Museum", b =>
                {
                    b.Navigation("Paintings");
                });

            modelBuilder.Entity("Database.Models.Painting", b =>
                {
                    b.Navigation("Exhibitions");
                });
#pragma warning restore 612, 618
        }
    }
}
